### ISSUE TITLE
Game End

### ISSUE THREAD

**Issue by taggartdev** [johnying7/Five-Minute-Puzzle#10]
**Requirements**
N/A

**As a** Developer
**I want** a Game End Scene
**So that** the player can understand the game is complete
**And** how to exit the game.

**Acceptance Criteria**

- A simple blank screen, no more interactive elements.
- Message displayed stating that the game is over.
- Message displayed explaining to press ESC to quit.
- Implement exiting the game by hitting Escape Key

**Comment by johnying7** [comment]
The way you've worded this issue, it fits more to change Player to Developer to more clearly define what the point of this issue/feature is. There is no guarantee the player will want to feel that way, but as a Developer, the purpose makes more sense.
Changing **I want** because it encapsulates several features other than just a screen. I also recommend adding directions for the player to his ESC to quit the game, because they may not know that keyboard key is a feature without directions. A quit game button might be more intuitive instead, making it the only interactive element left of the game.

**As a** Developer
**I want** a Game End Scene
**So that** the player can understand the game is complete
**And** how to exit the game

**Acceptance Criteria**
[Remove this line but rework this section to include the button or text explaining the ESC key]
- A simple blank screen, no more interactive elements.
- Text drawn stating that the game is over.
- ESC to quit.

**Comment by johnying7** [comment]
I don't know if I simply missed this or something, but you don't have requirements on this. I'm going to add Requirements into it. Make sure that if there aren't any requirements, put N/A. When you're browsing through the list on a computer, being able to mouse over and see if there are any requirements tied to a task helps quickly narrow down the important parts and let's everyone know that it wasn't forgotten but intentionally set to not have any requirements. I'm assuming also that you want the actual implementation for escape to quit the game. You want both the text explaining it and the feature both in this.
