### ISSUE TITLE
Collectible Coins

### ISSUE THREAD

**Issue by taggartdev** [johnying7/Five-Minute-Puzzle#5]
**Requirements**
#6 
#8 

**As a** Player
**I want** collectibles/coins
**So that** I can open puzzle doors
**And** win the game.

**Acceptance Criteria**

- Spinning yellow cylinder as placeholder Coin asset.
- Coin counter increments by 1 upon collision with player, i.e. collection. 
- Each coin vanishes permanently when collected.
- When the counter reaches a predetermined number
     - Operate a Door
     - Win the Game/Trigger Game End

**Comment by johnying7** [comment]
- You can remove "added variety to simple puzzles" since that isn't part of the creating of actual mechanics.
- Switch "Designer" to "Player" since this will be the person actually using the feature.
- Change **So that** line to "**So that** I can open puzzle doors".
- In the line right under **So that**, put "**And** win the game"
- Add the #6 Binary Doors issue as a requirement
- For the last acceptance criteria, that needs to be its own task which should be set as a requirement before this task is complete as well.
- Change last two acceptance criteria to be a little more abstract like make a two-tiered bulleted list where the first tier is "When counter reaches predetermined number" and second tier is "operates a door" and "end the game".

It may seem weird going backwards but try and think if getting all of the collectibles wins the game, how do you end the game when that code hasn't been written yet? I could write most of the code, but I'll end up doubling back. It's easier to make the Game End task first, then do this to complete it. Another thing to help visualize, imagine this is a massive game and at some point we decide to change what wins the game or what getting all of the collectibles does. It helps both you and me visualize and rework the feature if the tasks are separate.

**Comment by johnying7** [comment]
- Capitalize **and** to **And**.
- Notice how you did the game end trigger and #10 as a requirement? Your requirement is flip-flopped. Add #6 as an issue requirement.
- There's also a cylinder prefab in this game. It makes more sense to use a yellow material modified cylinder as the coin prefab instead. Change the acceptance criteria to that.

**Comment by johnying7** [comment]
Just noticed, this should also include #8 as a requirement. You first need a player to collide with in order to collect coins.
