### ISSUE TITLE
Coin Operated Doors

### ISSUE THREAD

**Issue by taggartdev** [johnying7/Five-Minute-Puzzle#6]
**Requirements**
N/A

**As a** Player
**I want** Coin Operated Doors
**So that** coins I collect unlock new areas 

**Acceptance Criteria**

- Doors have 2 notables states, opened and closed. 
- Initial state is closed.
- A number representing the amount of coins required is determined on a per-door basis
- When the player is within a predetermined distance of a door, that door's required coin amount should appear drawn on the GUI layer at the door's onscreen position, regardless of whether it is open or closed.
- When the number of coins reaches the predetermined requirement, the door will open upon collision with the player.
- The door opens by rotating clockwise 90 degrees. It's origin of rotation rests in the right side of the door as the player is facing it. This ensures the door will always open inward, and away from the player. 
- As there are no known recorded events of this happening in the wild, pictures provided are merely an artist's interpretation of the phenomenon. 

![image](https://user-images.githubusercontent.com/60831717/76162214-755f4800-6109-11ea-9695-9d99c3c714a2.png)

**Comment by johnying7** [comment]
- **So that** is more of what the purpose of the doors is supposed to do for the game. I know what you mean with doors, but things can get dicey when things are more complicated. You want it more along the lines of **So that** I can stop the player from getting to the next room or **So that** it can block the player from going back, or I think maybe in your case, something like **So that** the player has to strategically solve which door to open. Kind of what you envision to be the purpose of the feature.
- Create a task for the button system and in that requirement, reference this task (don't forget to reference how the button is activated. by the sounds of this, it isn't aimed at and used but stepped on. This wouldn't be part of the description but the Acceptance Criteria).
- I would probably make another task where you describe how you want the door to open and close (for example, is it a sliding door, rotating door, secret passage door, door to another dimension, etc). I'm exaggerating the last 2, but it helps with why you should include it.
- Last acceptance criteria should be removed and included in the button task. By the way, do you want the button to switch states of EVERY door in the game, or just the ones you (the designer) want to? Based on your wording, you would have every door changing and you as the designer wouldn't have the flexibility to decide if other doors don't change at all. If that's what you want, I can do that.

**Comment by johnying7** [comment]
- Remove **and** feel meaningful to collect. That part is implied by the functionality of the system.
- Your requirement is flip-flopped with #5. Set this issue requirement to N/A.

**Comment by johnying7** [comment]
Will the player know that a door is available to be opened by walking into it after collecting the required amount of coins?

**Comment by taggartdev** [comment]
> Will the player know that a door is available to be opened by walking into it after collecting the required amount of coins?

@johnying7 
Added to acceptance criteria:

When the player is within a predetermined distance of a door, that door's required coin amount should appear drawn on the GUI layer at the door's onscreen position, regardless of whether it is open or closed.

**Comment by johnying7** [comment]
@taggartdev
