### ISSUE TITLE
Player Controlled Character

### ISSUE THREAD

**Issue by taggartdev** [johnying7/Five-Minute-Puzzle#8]
**Requirements**
N/A

**As a** Player
**I want** a controllable player character
**So that** I can explore and interact with the game world.

**Acceptance Criteria**

- Player Character can be controlled with WASD, Jumping with Spacebar.
- Collides with both Terrain and imported 3D Objects
- Top Down Camera View, locked to player's position, does not rotate with player.

I believe the pack-in Unity 3RD Person Controller Satisfies these criteria.

**Comment by johnying7** [comment]
In the future, you won't need to set #1 as a requirement for two reasons.
- The way you've structured the requirement, every issue created in the future would also need to have #1 as a requirement, which would end up cluttering things and being a bit redundant.
- Since #1 has already been merged into the master branch as of creation of this issue, you don't really need to include it as a requirement. There might be a case where you would want a closed issue as a requirement (not sure if I could think of one), but it would most likely be to help clarify the structure of a complex feature.

**Comment by johnying7** [comment]
@taggartdev tagging
